name: Docker Build and test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
        
          node-version: 14

      - name: buiold the Docker Image
        run: docker build -t mirko7/service-web-store-lab4:mirko7/service-web-store-lab4 .

      - name: log in to the ole Docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.MYTOKEN }}

      - name: push the docker to the silly little dockerhub
        run: docker push mirko7/service-web-store-lab4:mirko7/service-web-store-lab4
